openapi: 3.1.0
info:
  title: SPY Options API
  description: API for fetching SPY OHLC, IV, Greeks, Market Tide, Spot GEX, and Bid/Ask Volume data.
  version: 1.2.0
servers:
  - url: https://spy-options-api.onrender.com

paths:
  /api/spy/ohlc:
    get:
      summary: Get SPY OHLC data
      operationId: getSPYOHLC
      description: Fetch the Open, High, Low, Close (OHLC) data for SPY.
      responses:
        "200":
          description: Successfully retrieved OHLC data.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    open:
                      type: number
                    high:
                      type: number
                    low:
                      type: number
                    close:
                      type: number
                    volume:
                      type: integer
                    total_volume:
                      type: integer
                    start_time:
                      type: string
                      format: date-time
                    end_time:
                      type: string
                      format: date-time

  /api/spy/ohlc-summary:
    get:
      summary: Get Daily SPY OHLC Summary (Latest)
      operationId: getSpyOhlcSummary
      responses:
        '200':
          description: Latest daily summary of SPY OHLC data with dealer exposure and volatility.
          content:
            application/json:
              schema:
                type: object
                properties:
                  trade_date:
                    type: string
                    format: date
                  open:
                    type: number
                  high:
                    type: number
                  low:
                    type: number
                  close:
                    type: number
                  total_volume:
                    type: integer
                  spot_price:
                    type: number
                  spot_gamma_oi:
                    type: number
                  spot_charm_oi:
                    type: number
                  spot_vanna_oi:
                    type: number
                  implied_volatility:
                    type: number
                  vwap:                        
                    type: number

  /api/spy/spot-gex:
    get:
      summary: Get SPY Spot GEX
      operationId: getSPYSpotGEX
      description: Fetch the latest SPY Spot Gamma Exposure (GEX) data.
      responses:
        "200":
          description: Successfully retrieved SPY Spot GEX data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  price:
                    type: number
                  charm_oi:
                    type: number
                  gamma_oi:
                    type: number
                  vanna_oi:
                    type: number
                  time:
                    type: string
                    format: date-time

  /api/spy/iv/0dte:
    get:
      summary: Get SPY Implied Volatility (0 DTE)
      operationId: getSPYIV0DTE
      description: Fetch the latest SPY 0 DTE Implied Volatility data and the last 5 available records.
      responses:
        "200":
          description: Successfully retrieved IV data for SPY (0 DTE).
          content:
            application/json:
              schema:
                type: object
                properties:
                  latest:
                    type: object
                    properties:
                      symbol:
                        type: string
                        example: "SPY"
                      date:
                        type: string
                        format: date
                        example: "2025-03-25"
                      expiry:
                        type: string
                        format: date
                        example: "2025-03-25"
                      dte:
                        type: integer
                        example: 0
                      implied_move:
                        type: number
                        example: 1.7000
                      implied_move_perc:
                        type: number
                        example: 0.00295
                      volatility:
                        type: number
                        example: 0.1751
                      recorded_at:
                        type: string
                        format: date-time
                        example: "2025-03-26T02:32:00.200Z"
                  last_5:
                    type: array
                    items:
                      type: object
                      properties:
                        symbol:
                          type: string
                        date:
                          type: string
                          format: date
                        expiry:
                          type: string
                          format: date
                        dte:
                          type: integer
                        implied_move:
                          type: number
                        implied_move_perc:
                          type: number
                        volatility:
                          type: number
                        recorded_at:
                          type: string
                          format: date-time

  /api/spy/market-tide:
    get:
      summary: Get the last 10 SPY Market Tide records
      operationId: getMarketTideList
      description: Returns the 10 most recent Market Tide records (5-minute intervals)
      responses:
        "200":
          description: Successfully retrieved list of market tide entries.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      format: date
                    timestamp:
                      type: string
                      format: date-time
                    net_call_premium:
                      type: number
                    net_put_premium:
                      type: number
                    net_volume:
                      type: integer
                    recorded_at:
                      type: string
                      format: date-time

  /api/spy/market-tide/latest:
    get:
      summary: Get the latest Market Tide data
      description: Returns the most recent Market Tide record (5-minute interval)
      responses:
        "200":
          description: Latest Market Tide record
          content:
            application/json:
              schema:
                type: object

  /api/spy/market-tide/deltas/today:
    get:
      summary: Get today's Market Tide delta trends
      description: Returns all delta trend entries for the current trading day
      responses:
        "200":
          description: Array of delta records with sentiment labels
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    timestamp:
                      type: string
                      format: date-time
                    delta_call:
                      type: number
                    delta_put:
                      type: number
                    delta_volume:
                      type: integer
                    sentiment:
                      type: string

  /api/spy/market-tide/snapshot:
    get:
      summary: Get full Market Tide sentiment snapshot
      description: Combines latest tide, rolling averages, and sentiment delta
      responses:
        "200":
          description: Full snapshot of institutional sentiment
          content:
            application/json:
              schema:
                type: object
                properties:
                  latest_tide:
                    type: object
                  rolling_avg:
                    type: object
                  latest_delta:
                    type: object

  /api/spy/greeks:
    get:
      summary: Get SPY Greeks by Strike
      operationId: getSPYGreeks
      description: Fetch top 5 Call GEX and top 5 Put GEX data for SPY.
      responses:
        "200":
          description: Successfully retrieved Greeks by Strike data.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    strike:
                      type: number
                    call_gex:
                      type: number
                    put_gex:
                      type: number
                    call_delta:
                      type: number
                    put_delta:
                      type: number
                    call_vanna:
                      type: number
                    put_vanna:
                      type: number
                    call_charm:
                      type: number
                    put_charm:
                      type: number
                    price:
                      type: number
                    time:
                      type: string
                      format: date-time

  /api/spy/option-price-levels/today:
    get:
      summary: Get Today's SPY Option Price Levels
      operationId: getSPYOptionPriceLevelsToday
      description: Fetch today's SPY option price levels by volume.
      responses:
        "200":
          description: Successfully retrieved today's SPY Option Price Levels.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    price:
                      type: number
                    call_volume:
                      type: integer
                    put_volume:
                      type: integer
                    total_volume:
                      type: integer
                    time:
                      type: string
                      format: date

  /api/spy/bid-ask-volume:
    get:
      summary: Get SPY Bid/Ask Volume Data
      operationId: getSPYBidAskVolume
      description: Fetch the bid/ask volume data for SPY, SPX, QQQ, and NDX.
      responses:
        "200":
          description: Successfully retrieved Bid/Ask Volume data.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ticker:
                      type: string
                    avg_30_day_call_volume:
                      type: number
                    avg_30_day_put_volume:
                      type: number
                    avg_3_day_call_volume:
                      type: number
                    avg_3_day_put_volume:
                      type: number
                    avg_7_day_call_volume:
                      type: number
                    avg_7_day_put_volume:
                      type: number
                    bearish_premium:
                      type: number
                    bullish_premium:
                      type: number
                    call_open_interest:
                      type: integer
                    put_open_interest:
                      type: integer
                    call_premium:
                      type: number
                    put_premium:
                      type: number
                    call_volume:
                      type: integer
                    put_volume:
                      type: integer
                    call_volume_ask_side:
                      type: integer
                    put_volume_ask_side:
                      type: integer
                    call_volume_bid_side:
                      type: integer
                    put_volume_bid_side:
                      type: integer
                    net_call_premium:
                      type: number
                    net_put_premium:
                      type: number
                    date:
                      type: string
                      format: date

  /api/greek-exposure:
    get:
      summary: Fetch the last 5 Greek Exposure records for SPY or SPX
      operationId: getGreekExposure
      parameters:
        - name: symbol
          in: query
          required: true
          schema:
            type: string
            enum: [SPY, SPX]
          description: The symbol for which to fetch Greek Exposure data (SPY or SPX)
      responses:
        "200":
          description: Successful response with Greek Exposure data.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    symbol:
                      type: string
                    date:
                      type: string
                      format: date
                    call_charm:
                      type: number
                    call_delta:
                      type: number
                    call_gamma:
                      type: number
                    call_vanna:
                      type: number
                    put_charm:
                      type: number
                    put_delta:
                      type: number
                    put_gamma:
                      type: number
                    put_vanna:
                      type: number
                    recorded_at:
                      type: string
                      format: date-time
