openapi: 3.1.0
info:
  title: SPY Options API
  description: API for fetching SPY OHLC, IV, Greeks, Market Tide, Spot GEX, and Bid/Ask Volume data.
  version: 1.2.0
servers:
  - url: https://spy-options-api.onrender.com

paths:
  /api/spy/ohlc:
    get:
      summary: Get SPY OHLC data
      operationId: getSPYOHLC
      description: Fetch the Open, High, Low, Close (OHLC) data for SPY.
      responses:
        "200":
          description: Successfully retrieved OHLC data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  open:
                    type: number
                  high:
                    type: number
                  low:
                    type: number
                  close:
                    type: number
                  total_volume:
                    type: integer
                  volume:
                    type: integer
                  start_time:
                    type: string
                    format: date-time
                  end_time:
                    type: string
                    format: date-time

  /api/spy/spot-gex:
    get:
      summary: Get SPY Spot GEX
      operationId: getSPYSpotGEX
      description: Fetch the latest SPY Spot Gamma Exposure (GEX) data.
      responses:
        "200":
          description: Successfully retrieved SPY Spot GEX data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  price:
                    type: number
                  charm_oi:
                    type: number
                  gamma_oi:
                    type: number
                  vanna_oi:
                    type: number
                  time:
                    type: string
                    format: date-time

  /api/spy/iv:
    get:
      summary: Get SPY Implied Volatility (5 DTE)
      operationId: getSPYIV
      description: Fetch SPY's 5-day DTE implied volatility data.
      responses:
        "200":
          description: Successfully retrieved IV data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  implied_move:
                    type: number
                  implied_move_perc:
                    type: number
                  volatility:
                    type: number
                  expiry:
                    type: string
                  dte:
                    type: integer

  /api/spy/market-tide:
    get:
      summary: Get SPY Market Tide Data
      operationId: getSPYMarketTide
      description: Fetch the latest Market Tide data along with rolling averages for SPY.
      responses:
        "200":
          description: Successfully retrieved market tide data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  latest:
                    type: object
                    description: The most recent market tide data.
                    properties:
                      net_call_premium:
                        type: number
                        description: Net call premium from the latest interval.
                      net_put_premium:
                        type: number
                        description: Net put premium from the latest interval.
                      net_volume:
                        type: number
                        description: Net volume from the latest interval.
                      timestamp:
                        type: string
                        format: date-time
                        description: Timestamp of the latest market tide data.
                  rolling_averages:
                    type: object
                    description: Rolling averages for the last 12 and 48 intervals.
                    properties:
                      avg_net_call_premium_12_intervals:
                        type: number
                        description: Average net call premium over the last 12 intervals (5-minute each).
                      avg_net_put_premium_12_intervals:
                        type: number
                        description: Average net put premium over the last 12 intervals (5-minute each).
                      avg_net_volume_12_intervals:
                        type: number
                        description: Average net volume over the last 12 intervals (5-minute each).
                      avg_net_call_premium_48_intervals:
                        type: number
                        description: Average net call premium over the last 48 intervals (5-minute each).
                      avg_net_put_premium_48_intervals:
                        type: number
                        description: Average net put premium over the last 48 intervals (5-minute each).
                      avg_net_volume_48_intervals:
                        type: number
                        description: Average net volume over the last 48 intervals (5-minute each).
                      recorded_at:
                        type: string
                        format: date-time
                        description: Timestamp of when the rolling averages were recorded.

  /api/spy/greeks:
    get:
      summary: Get SPY Greeks by Strike
      operationId: getSPYGreeks
      description: Fetch top 5 Call GEX and top 5 Put GEX data for SPY.
      responses:
        "200":
          description: Successfully retrieved Greeks by Strike data.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    strike:
                      type: number
                    call_gex:
                      type: number
                    put_gex:
                      type: number
                    call_delta:
                      type: number
                    put_delta:
                      type: number
                    call_vanna:
                      type: number
                    put_vanna:
                      type: number
                    call_charm:
                      type: number
                    put_charm:
                      type: number
                    price:
                      type: number
                    time:
                      type: string
                      format: date-time

  /api/spy/option-price-levels:
    get:
      summary: Get SPY Option Price Levels
      operationId: getSPYOptionPriceLevels
      description: Fetch the top 10 SPY option price levels by volume.
      responses:
        "200":
          description: Successfully retrieved SPY Option Price Levels.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    price:
                      type: number
                    call_volume:
                      type: integer
                    put_volume:
                      type: integer
                    total_volume:
                      type: integer
                    time:
                      type: string
                      format: date-time

  /api/spy/bid-ask-volume:
    get:
      summary: Get SPY Bid/Ask Volume Data
      operationId: getSPYBidAskVolume
      description: Fetch the bid/ask volume data for SPY, SPX, QQQ, and NDX.
      responses:
        "200":
          description: Successfully retrieved Bid/Ask Volume data.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ticker:
                      type: string
                    avg_30_day_call_volume:
                      type: number
                    avg_30_day_put_volume:
                      type: number
                    avg_3_day_call_volume:
                      type: number
                    avg_3_day_put_volume:
                      type: number
                    avg_7_day_call_volume:
                      type: number
                    avg_7_day_put_volume:
                      type: number
                    bearish_premium:
                      type: number
                    bullish_premium:
                      type: number
                    call_open_interest:
                      type: integer
                    put_open_interest:
                      type: integer
                    call_premium:
                      type: number
                    put_premium:
                      type: number
                    call_volume:
                      type: integer
                    put_volume:
                      type: integer
                    call_volume_ask_side:
                      type: integer
                    put_volume_ask_side:
                      type: integer
                    call_volume_bid_side:
                      type: integer
                    put_volume_bid_side:
                      type: integer
                    net_call_premium:
                      type: number
                    net_put_premium:
                      type: number
                    date:
                      type: string
                      format: date

  /api/greek-exposure:
    get:
      summary: Fetch the last 5 Greek Exposure records for SPY or SPX
      operationId: getGreekExposure
      parameters:
        - name: symbol
          in: query
          required: true
          schema:
            type: string
            enum: [SPY, SPX]
          description: The symbol for which to fetch Greek Exposure data (SPY or SPX)
      responses:
        "200":
          description: Successful response with Greek Exposure data.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    symbol:
                      type: string
                    date:
                      type: string
                      format: date
                    call_charm:
                      type: number
                    call_delta:
                      type: number
                    call_gamma:
                      type: number
                    call_vanna:
                      type: number
                    put_charm:
                      type: number
                    put_delta:
                      type: number
                    put_gamma:
                      type: number
                    put_vanna:
                      type: number
                    recorded_at:
                      type: string
                      format: date-time
